import { Movie, ReleaseDates } from './types';

export const trendingResultDummy = {
  page: 1,
  results: [
    {
      genre_ids: [14, 28, 12],
      title: 'Doctor Strange in the Multiverse of Madness',
      original_language: 'en',
      original_title: 'Doctor Strange in the Multiverse of Madness',
      poster_path: '/wRnbWt44nKjsFPrqSmwYki5vZtF.jpg',
      id: 453395,
      video: false,
      vote_average: 7.6,
      overview:
        'Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.',
      release_date: '2022-05-04',
      adult: false,
      backdrop_path: '/AdyJH8kDm8xT8IKTlgpEC15ny4u.jpg',
      vote_count: 723,
      popularity: 5201.375,
      media_type: 'movie',
    },
    {
      overview:
        'After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.',
      release_date: '2022-03-30',
      adult: false,
      backdrop_path: '/egoyMDLqCxzjnSrWOz50uLlJWmD.jpg',
      vote_count: 1019,
      genre_ids: [28, 878, 35, 10751, 12],
      id: 675353,
      original_language: 'en',
      original_title: 'Sonic the Hedgehog 2',
      poster_path: '/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg',
      title: 'Sonic the Hedgehog 2',
      video: false,
      vote_average: 7.7,
      popularity: 10135.117,
      media_type: 'movie',
    },
    {
      id: 92749,
      original_name: 'Moon Knight',
      origin_country: ['US'],
      genre_ids: [10759, 10765, 9648],
      original_language: 'en',
      poster_path: '/YksR65as1ppF2N48TJAh2PLamX.jpg',
      vote_count: 662,
      vote_average: 8.4,
      first_air_date: '2022-03-30',
      name: 'Moon Knight',
      overview:
        'When Steven Grant, a mild-mannered gift-shop employee, becomes plagued with blackouts and memories of another life, he discovers he has dissociative identity disorder and shares a body with mercenary Marc Spector. As Steven/Marc’s enemies converge upon them, they must navigate their complex identities while thrust into a deadly mystery among the powerful gods of Egypt.',
      backdrop_path: '/1uegR4uAxRxiMyX4nQnpzbXhrTw.jpg',
      popularity: 4990.135,
      media_type: 'tv',
    },
    {
      video: false,
      vote_average: 6.1,
      overview:
        'Ousmane Diakité and François Monge are two cops with very different styles, backgrounds and careers. The unlikely pair are reunited once again for a new investigation that takes them across France. What seemed to be a simple drug deal turns out to be a much bigger criminal case wrapped in danger and unexpected comedy.',
      release_date: '2022-05-06',
      adult: false,
      backdrop_path: '/wtbRUVxQVvU6QIJH1oGLDThJLib.jpg',
      vote_count: 25,
      genre_ids: [35, 28],
      title: 'The Takedown',
      original_language: 'fr',
      original_title: 'Loin du périph',
      poster_path: '/h5hVeCfYSb8gIO0F41gqidtb0AI.jpg',
      id: 785985,
      popularity: 66.577,
      media_type: 'movie',
    },
    {
      poster_path: '/7qop80YfuO0BwJa1uXk1DXUUEwv.jpg',
      video: false,
      vote_average: 7.8,
      overview:
        'When the infamous Bad Guys are finally caught after years of countless heists and being the world’s most-wanted villains, Mr. Wolf brokers a deal to save them all from prison.',
      release_date: '2022-03-17',
      vote_count: 250,
      adult: false,
      backdrop_path: '/fEe5fe82qHzjO4yej0o79etqsWV.jpg',
      title: 'The Bad Guys',
      genre_ids: [16, 35, 28, 10751, 80],
      id: 629542,
      original_language: 'en',
      original_title: 'The Bad Guys',
      popularity: 3067.401,
      media_type: 'movie',
    },
    {
      video: false,
      vote_average: 7.2,
      overview:
        'A young street-smart, Nathan Drake and his wisecracking partner Victor “Sully” Sullivan embark on a dangerous pursuit of “the greatest treasure never found” while also tracking clues that may lead to Nathan’s long-lost brother.',
      release_date: '2022-02-10',
      adult: false,
      backdrop_path: '/aEGiJJP91HsKVTEPy1HhmN0wRLm.jpg',
      vote_count: 1716,
      genre_ids: [28, 12],
      title: 'Uncharted',
      original_language: 'en',
      original_title: 'Uncharted',
      poster_path: '/tlZpSxYuBRoVJBOpUrPdQe9FmFq.jpg',
      id: 335787,
      popularity: 5928.925,
      media_type: 'movie',
    },
    {
      id: 778106,
      original_language: 'en',
      original_title: 'Along for the Ride',
      poster_path: '/d5spmLeGR9kxBRQ6qxCFad1ljvT.jpg',
      video: false,
      vote_average: 7.2,
      overview:
        'The summer before college Auden meets the mysterious Eli, a fellow insomniac. While the seaside town of Colby sleeps, the two embark on a nightly quest to help Auden experience the fun, carefree teen life she never knew she wanted.',
      release_date: '2022-05-06',
      title: 'Along for the Ride',
      adult: false,
      backdrop_path: '/xqlxMhXkLGHHDiFwVYzYTayUFyA.jpg',
      vote_count: 20,
      genre_ids: [10749, 18],
      popularity: 59.83,
      media_type: 'movie',
    },
    {
      poster_path: '/iwIdajr5Y4zq2ibvq75VnDAJBr.jpg',
      id: 103516,
      overview:
        'Follow Christopher Pike, Spock and Number One in the years before Captain Kirk boarded the U.S.S. Enterprise, as they explore new worlds around the galaxy.',
      vote_count: 19,
      original_name: 'Star Trek: Strange New Worlds',
      origin_country: ['US'],
      first_air_date: '2022-05-05',
      vote_average: 8.1,
      genre_ids: [10765],
      backdrop_path: '/rzAzvWJoZSwVSswvWsKx1lqT63m.jpg',
      original_language: 'en',
      name: 'Star Trek: Strange New Worlds',
      popularity: 179.497,
      media_type: 'tv',
    },
    {
      poster_path: '/74xTEgt7R36Fpooo50r9T25onhq.jpg',
      video: false,
      vote_average: 7.8,
      overview:
        'In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.',
      release_date: '2022-03-01',
      vote_count: 4314,
      adult: false,
      backdrop_path: '/5P8SmMzSNYikXpxil6BYzJ16611.jpg',
      title: 'The Batman',
      genre_ids: [80, 9648, 53],
      id: 414906,
      original_language: 'en',
      original_title: 'The Batman',
      popularity: 5709.032,
      media_type: 'movie',
    },
    {
      original_language: 'pl',
      original_title: '365 Days: This Day',
      poster_path: '/7qU0SOVcQ8BTJLodcAlulUAG16C.jpg',
      video: false,
      vote_average: 5.8,
      id: 829557,
      overview:
        "Laura and Massimo are back and hotter than ever. But the reunited couple's new beginning is complicated by Massimo’s family ties and a mysterious man who enters Laura’s life to win her heart and trust, at any cost.",
      release_date: '2022-04-27',
      adult: false,
      backdrop_path: '/zBG5Mg29NH9xxpWMMG7BIvKwYhL.jpg',
      vote_count: 307,
      genre_ids: [10749, 18],
      title: '365 Days: This Day',
      popularity: 2626.746,
      media_type: 'movie',
    },
    {
      overview:
        'Great Dane Marmaduke epitomizes the overgrown lapdog, with an irascible streak and a penchant for mischief that is tempered with a deep sense of love and responsibility for his human family, the Winslows. The new animation is set in the world of elite dog shows, rife divas, rivalries and slapstick comedy.',
      release_date: '2022-04-28',
      adult: false,
      backdrop_path: '/f8F4XgaIXidVLqmJGYFP9jHH08Y.jpg',
      vote_count: 2,
      genre_ids: [16, 10751, 35],
      id: 678287,
      original_language: 'en',
      original_title: 'Marmaduke',
      poster_path: '/u5QyYu3tVfhHyleHU1hIw3ZMQCN.jpg',
      title: 'Marmaduke',
      video: false,
      vote_average: 5.0,
      popularity: 25.882,
      media_type: 'movie',
    },
    {
      adult: false,
      backdrop_path: '/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg',
      genre_ids: [28, 12, 878],
      original_language: 'en',
      original_title: 'Spider-Man: No Way Home',
      poster_path: '/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
      vote_count: 12476,
      video: false,
      vote_average: 8.1,
      title: 'Spider-Man: No Way Home',
      overview:
        'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
      release_date: '2021-12-15',
      id: 634649,
      popularity: 4511.964,
      media_type: 'movie',
    },
    {
      original_language: 'es',
      id: 128010,
      original_name: 'Bienvenidos a Edén',
      origin_country: ['ES'],
      vote_average: 8.8,
      name: 'Welcome to Eden',
      vote_count: 5,
      poster_path: '/kZO0mtTHAgg9QVscLVtwCcQ7Hgx.jpg',
      backdrop_path: '/AftVTQuXw2R0SZkSLPZ4aZB72LJ.jpg',
      overview:
        'Are you happy? With this question, Zoa and four other attractive young people, very active on social networks, are invited to the most exclusive party in history on a secret island, organized by the brand of a new drink. What begins as an exciting journey will soon become the journey of a lifetime. But paradise is not really what it seems - Welcome to Eden.',
      genre_ids: [10759],
      first_air_date: '2022-05-06',
      popularity: 111.569,
      media_type: 'tv',
    },
    {
      genre_ids: [80, 18],
      original_language: 'en',
      poster_path: '/9Z7L7wSB6nLwWk7coUgm1ytQbOB.jpg',
      id: 153657,
      vote_average: 9.0,
      overview:
        "Bosch is now making a living as a private investigator two years after he quit the LAPD and finds himself working with one time enemy and top-notch attorney Honey “Money” Chandler. Meanwhile, Bosch's daughter Maddie is venturing into the world of the LAPD.",
      original_name: 'Bosch: Legacy',
      origin_country: ['US'],
      vote_count: 7,
      name: 'Bosch: Legacy',
      backdrop_path: '/wVGiwvE5CtlVPrP0oEO3W70ft6D.jpg',
      first_air_date: '2022-05-05',
      popularity: 46.918,
      media_type: 'tv',
    },
    {
      overview:
        'An enigmatic magician living in an abandoned amusement park introduces magic into the life of a high schooler struggling with harsh realities.',
      name: 'The Sound of Magic',
      backdrop_path: '/tX5W2a0B9r4cs25G78tKjNv76Gj.jpg',
      vote_count: 3,
      genre_ids: [18, 10765],
      origin_country: ['KR'],
      first_air_date: '2022-05-06',
      original_name: '안나라수마나라',
      poster_path: '/jrWM82Hie9DAkoDzXh3pxAFwf9d.jpg',
      id: 123349,
      original_language: 'ko',
      vote_average: 8.3,
      popularity: 74.621,
      media_type: 'tv',
    },
    {
      overview:
        'Depicting an epic 26th-century conflict between humanity and an alien threat known as the Covenant, the series weaves deeply drawn personal stories with action, adventure and a richly imagined vision of the future.',
      name: 'Halo',
      backdrop_path: '/1qpUk27LVI9UoTS7S0EixUBj5aR.jpg',
      vote_count: 572,
      genre_ids: [10759, 10765],
      origin_country: ['US'],
      first_air_date: '2022-03-24',
      original_name: 'Halo',
      poster_path: '/nJUHX3XL1jMkk8honUZnUmudFb9.jpg',
      id: 52814,
      original_language: 'en',
      vote_average: 8.7,
      popularity: 5238.03,
      media_type: 'tv',
    },
    {
      adult: false,
      backdrop_path: '/192vHmAPbk5esL34XMKZ1YLGFjr.jpg',
      genre_ids: [28, 53, 80],
      id: 763285,
      original_language: 'en',
      original_title: 'Ambulance',
      overview:
        "Decorated veteran Will Sharp, desperate for money to cover his wife's medical bills, asks for help from his adoptive brother Danny. A charismatic career criminal, Danny instead offers him a score: the biggest bank heist in Los Angeles history: $32 million.",
      poster_path: '/kuxjMVuc3VTD7p42TZpJNsSrM1V.jpg',
      release_date: '2022-03-16',
      title: 'Ambulance',
      video: false,
      vote_average: 7.0,
      vote_count: 468,
      popularity: 3735.135,
      media_type: 'movie',
    },
    {
      id: 88584,
      first_air_date: '2022-05-05',
      name: 'The Pentaverate',
      backdrop_path: '/6lg8J79bB0jjTCEah9xyBrNtYSU.jpg',
      vote_count: 3,
      genre_ids: [35],
      vote_average: 6.0,
      original_language: 'en',
      original_name: 'The Pentaverate',
      origin_country: ['US'],
      poster_path: '/kY0AKRdYuaahPMcQL2jIxXRHvgf.jpg',
      overview:
        'After influencing global events for centuries, a secret society faces a dangerous threat from within. Can a Canadian reporter save them — and the world?',
      popularity: 92.295,
      media_type: 'tv',
    },
    {
      original_language: 'en',
      id: 113367,
      original_name: 'The Wilds',
      origin_country: ['US'],
      vote_average: 8.0,
      name: 'The Wilds',
      vote_count: 329,
      poster_path: '/gHBtyMdHbWoM3tpM8VZymer8HfF.jpg',
      backdrop_path: '/jke7vRfAfwViuwfJhuhzlpxQuHY.jpg',
      overview:
        "A group of teen girls from different backgrounds must fight for survival after a plane crash strands them on a deserted island. The castaways both clash and bond as they learn more about each other, the secrets they keep, and the traumas they've all endured. But there’s just one twist… these girls did not end up on this island by accident.",
      genre_ids: [9648, 18],
      first_air_date: '2020-12-11',
      popularity: 168.84,
      media_type: 'tv',
    },
    {
      adult: false,
      backdrop_path: '/4rON0QFWpHtZ9bEtfdE68TFbfGr.jpg',
      genre_ids: [53, 27],
      original_language: 'en',
      original_title: 'Escape the Field',
      poster_path: '/3qDumKWwi3YZacMI9u2UoPHWVDi.jpg',
      vote_count: 11,
      video: false,
      vote_average: 6.1,
      title: 'Escape the Field',
      overview:
        'Six strangers suddenly awaken in a remote, endless cornfield. Stripped of their possessions, they are left with only six items: a gun with a single bullet, matches, a lantern, a knife, a compass, and a flask of water. As mysterious sirens blare in the distance and traps appear at every turn, the group realizes it’s been plunged into a cat-and-mouse game with an unseen evil, and survival depends upon solving a diabolical and deadly puzzle.',
      release_date: '2022-05-06',
      id: 739643,
      popularity: 78.59,
      media_type: 'movie',
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};

export const featuredMovieDummy: Movie = {
  adult: false,
  backdrop_path: '/AdyJH8kDm8xT8IKTlgpEC15ny4u.jpg',
  belongs_to_collection: {
    id: 618529,
    name: 'Doctor Strange Collection',
    poster_path: '/bm7UlW3ctMJAvD6NNXrCDdRyyKn.jpg',
    backdrop_path: '/5ZuctJh5uX5L2dz1CjA7WsTJwZk.jpg',
  },
  budget: 200000000,
  genres: [
    {
      id: 14,
      name: 'Fantasy',
    },
    {
      id: 28,
      name: 'Action',
    },
    {
      id: 12,
      name: 'Adventure',
    },
  ],
  homepage:
    'https://www.marvel.com/movies/doctor-strange-in-the-multiverse-of-madness',
  id: 453395,
  imdb_id: 'tt9419884',
  original_language: 'en',
  original_title: 'Doctor Strange in the Multiverse of Madness',
  overview:
    'Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.',
  popularity: 5201.375,
  poster_path: '/wRnbWt44nKjsFPrqSmwYki5vZtF.jpg',
  production_companies: [
    {
      id: 420,
      logo_path: '/hUzeosd33nzE5MCNsZxCGEKTXaQ.png',
      name: 'Marvel Studios',
      origin_country: 'US',
    },
  ],
  production_countries: [
    {
      iso_3166_1: 'US',
      name: 'United States of America',
    },
  ],
  release_date: '2022-05-04',
  revenue: 229300000,
  runtime: 126,
  spoken_languages: [
    {
      english_name: 'Cantonese',
      iso_639_1: 'cn',
      name: '广州话 / 廣州話',
    },
    {
      english_name: 'English',
      iso_639_1: 'en',
      name: 'English',
    },
    {
      english_name: 'Spanish',
      iso_639_1: 'es',
      name: 'Español',
    },
  ],
  status: 'Released',
  tagline: 'Enter a new dimension of Strange.',
  title: 'Doctor Strange in the Multiverse of Madness',
  video: false,
  vote_average: 7.6,
  vote_count: 779,
};

export const releaseDatesDummy: ReleaseDates = {
  id: 453395,
  results: [
    {
      iso_3166_1: 'FR',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-04T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'CA',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-06T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'PT',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-05T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'PH',
      release_dates: [
        {
          certification: 'R-13',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-04T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'BR',
      release_dates: [
        {
          certification: '14',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-05T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'DE',
      release_dates: [
        {
          certification: '12',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-05T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'KR',
      release_dates: [
        {
          certification: '12',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-04T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'FI',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-06T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'IL',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-05T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'ES',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-06T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'TH',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-05T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'CZ',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-05T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'AT',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-04T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'SG',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-04T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'GR',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-05T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'SE',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-04T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'AU',
      release_dates: [
        {
          certification: 'M',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-05T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'HK',
      release_dates: [
        {
          certification: 'IIA',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-04T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'PL',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-06T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'TR',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-06T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'JP',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-04T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'GB',
      release_dates: [
        {
          certification: '12A',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-05T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'HU',
      release_dates: [
        {
          certification: '16',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-04T00:00:00.000Z',
          type: 1,
        },
        {
          certification: '16',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-05T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'UA',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-05T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'MK',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-05T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'US',
      release_dates: [
        {
          certification: 'PG-13',
          iso_639_1: '',
          note: 'Hollywood, California',
          release_date: '2022-05-02T00:00:00.000Z',
          type: 1,
        },
        {
          certification: 'PG-13',
          iso_639_1: null,
          note: '',
          release_date: '2022-05-06T00:00:00.000Z',
          type: 3,
        },
      ],
    },
  ],
};
