import { Credit, Movie, ReleaseDates } from './types';

export const trendingResultDummy = {
  page: 1,
  results: [
    {
      genre_ids: [14, 28, 12],
      title: 'Doctor Strange in the Multiverse of Madness',
      original_language: 'en',
      original_title: 'Doctor Strange in the Multiverse of Madness',
      poster_path: '/wRnbWt44nKjsFPrqSmwYki5vZtF.jpg',
      id: 453395,
      video: false,
      vote_average: 7.6,
      overview:
        'Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.',
      release_date: '2022-05-04',
      adult: false,
      backdrop_path: '/AdyJH8kDm8xT8IKTlgpEC15ny4u.jpg',
      vote_count: 723,
      popularity: 5201.375,
      media_type: 'movie',
    },
    {
      overview:
        'After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.',
      release_date: '2022-03-30',
      adult: false,
      backdrop_path: '/egoyMDLqCxzjnSrWOz50uLlJWmD.jpg',
      vote_count: 1019,
      genre_ids: [28, 878, 35, 10751, 12],
      id: 675353,
      original_language: 'en',
      original_title: 'Sonic the Hedgehog 2',
      poster_path: '/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg',
      title: 'Sonic the Hedgehog 2',
      video: false,
      vote_average: 7.7,
      popularity: 10135.117,
      media_type: 'movie',
    },
    {
      id: 92749,
      original_name: 'Moon Knight',
      origin_country: ['US'],
      genre_ids: [10759, 10765, 9648],
      original_language: 'en',
      poster_path: '/YksR65as1ppF2N48TJAh2PLamX.jpg',
      vote_count: 662,
      vote_average: 8.4,
      first_air_date: '2022-03-30',
      name: 'Moon Knight',
      overview:
        'When Steven Grant, a mild-mannered gift-shop employee, becomes plagued with blackouts and memories of another life, he discovers he has dissociative identity disorder and shares a body with mercenary Marc Spector. As Steven/Marc’s enemies converge upon them, they must navigate their complex identities while thrust into a deadly mystery among the powerful gods of Egypt.',
      backdrop_path: '/1uegR4uAxRxiMyX4nQnpzbXhrTw.jpg',
      popularity: 4990.135,
      media_type: 'tv',
    },
    {
      video: false,
      vote_average: 6.1,
      overview:
        'Ousmane Diakité and François Monge are two cops with very different styles, backgrounds and careers. The unlikely pair are reunited once again for a new investigation that takes them across France. What seemed to be a simple drug deal turns out to be a much bigger criminal case wrapped in danger and unexpected comedy.',
      release_date: '2022-05-06',
      adult: false,
      backdrop_path: '/wtbRUVxQVvU6QIJH1oGLDThJLib.jpg',
      vote_count: 25,
      genre_ids: [35, 28],
      title: 'The Takedown',
      original_language: 'fr',
      original_title: 'Loin du périph',
      poster_path: '/h5hVeCfYSb8gIO0F41gqidtb0AI.jpg',
      id: 785985,
      popularity: 66.577,
      media_type: 'movie',
    },
    {
      poster_path: '/7qop80YfuO0BwJa1uXk1DXUUEwv.jpg',
      video: false,
      vote_average: 7.8,
      overview:
        'When the infamous Bad Guys are finally caught after years of countless heists and being the world’s most-wanted villains, Mr. Wolf brokers a deal to save them all from prison.',
      release_date: '2022-03-17',
      vote_count: 250,
      adult: false,
      backdrop_path: '/fEe5fe82qHzjO4yej0o79etqsWV.jpg',
      title: 'The Bad Guys',
      genre_ids: [16, 35, 28, 10751, 80],
      id: 629542,
      original_language: 'en',
      original_title: 'The Bad Guys',
      popularity: 3067.401,
      media_type: 'movie',
    },
    {
      video: false,
      vote_average: 7.2,
      overview:
        'A young street-smart, Nathan Drake and his wisecracking partner Victor “Sully” Sullivan embark on a dangerous pursuit of “the greatest treasure never found” while also tracking clues that may lead to Nathan’s long-lost brother.',
      release_date: '2022-02-10',
      adult: false,
      backdrop_path: '/aEGiJJP91HsKVTEPy1HhmN0wRLm.jpg',
      vote_count: 1716,
      genre_ids: [28, 12],
      title: 'Uncharted',
      original_language: 'en',
      original_title: 'Uncharted',
      poster_path: '/tlZpSxYuBRoVJBOpUrPdQe9FmFq.jpg',
      id: 335787,
      popularity: 5928.925,
      media_type: 'movie',
    },
    {
      id: 778106,
      original_language: 'en',
      original_title: 'Along for the Ride',
      poster_path: '/d5spmLeGR9kxBRQ6qxCFad1ljvT.jpg',
      video: false,
      vote_average: 7.2,
      overview:
        'The summer before college Auden meets the mysterious Eli, a fellow insomniac. While the seaside town of Colby sleeps, the two embark on a nightly quest to help Auden experience the fun, carefree teen life she never knew she wanted.',
      release_date: '2022-05-06',
      title: 'Along for the Ride',
      adult: false,
      backdrop_path: '/xqlxMhXkLGHHDiFwVYzYTayUFyA.jpg',
      vote_count: 20,
      genre_ids: [10749, 18],
      popularity: 59.83,
      media_type: 'movie',
    },
    {
      poster_path: '/iwIdajr5Y4zq2ibvq75VnDAJBr.jpg',
      id: 103516,
      overview:
        'Follow Christopher Pike, Spock and Number One in the years before Captain Kirk boarded the U.S.S. Enterprise, as they explore new worlds around the galaxy.',
      vote_count: 19,
      original_name: 'Star Trek: Strange New Worlds',
      origin_country: ['US'],
      first_air_date: '2022-05-05',
      vote_average: 8.1,
      genre_ids: [10765],
      backdrop_path: '/rzAzvWJoZSwVSswvWsKx1lqT63m.jpg',
      original_language: 'en',
      name: 'Star Trek: Strange New Worlds',
      popularity: 179.497,
      media_type: 'tv',
    },
    {
      poster_path: '/74xTEgt7R36Fpooo50r9T25onhq.jpg',
      video: false,
      vote_average: 7.8,
      overview:
        'In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.',
      release_date: '2022-03-01',
      vote_count: 4314,
      adult: false,
      backdrop_path: '/5P8SmMzSNYikXpxil6BYzJ16611.jpg',
      title: 'The Batman',
      genre_ids: [80, 9648, 53],
      id: 414906,
      original_language: 'en',
      original_title: 'The Batman',
      popularity: 5709.032,
      media_type: 'movie',
    },
    {
      original_language: 'pl',
      original_title: '365 Days: This Day',
      poster_path: '/7qU0SOVcQ8BTJLodcAlulUAG16C.jpg',
      video: false,
      vote_average: 5.8,
      id: 829557,
      overview:
        "Laura and Massimo are back and hotter than ever. But the reunited couple's new beginning is complicated by Massimo’s family ties and a mysterious man who enters Laura’s life to win her heart and trust, at any cost.",
      release_date: '2022-04-27',
      adult: false,
      backdrop_path: '/zBG5Mg29NH9xxpWMMG7BIvKwYhL.jpg',
      vote_count: 307,
      genre_ids: [10749, 18],
      title: '365 Days: This Day',
      popularity: 2626.746,
      media_type: 'movie',
    },
    {
      overview:
        'Great Dane Marmaduke epitomizes the overgrown lapdog, with an irascible streak and a penchant for mischief that is tempered with a deep sense of love and responsibility for his human family, the Winslows. The new animation is set in the world of elite dog shows, rife divas, rivalries and slapstick comedy.',
      release_date: '2022-04-28',
      adult: false,
      backdrop_path: '/f8F4XgaIXidVLqmJGYFP9jHH08Y.jpg',
      vote_count: 2,
      genre_ids: [16, 10751, 35],
      id: 678287,
      original_language: 'en',
      original_title: 'Marmaduke',
      poster_path: '/u5QyYu3tVfhHyleHU1hIw3ZMQCN.jpg',
      title: 'Marmaduke',
      video: false,
      vote_average: 5.0,
      popularity: 25.882,
      media_type: 'movie',
    },
    {
      adult: false,
      backdrop_path: '/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg',
      genre_ids: [28, 12, 878],
      original_language: 'en',
      original_title: 'Spider-Man: No Way Home',
      poster_path: '/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
      vote_count: 12476,
      video: false,
      vote_average: 8.1,
      title: 'Spider-Man: No Way Home',
      overview:
        'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
      release_date: '2021-12-15',
      id: 634649,
      popularity: 4511.964,
      media_type: 'movie',
    },
    {
      original_language: 'es',
      id: 128010,
      original_name: 'Bienvenidos a Edén',
      origin_country: ['ES'],
      vote_average: 8.8,
      name: 'Welcome to Eden',
      vote_count: 5,
      poster_path: '/kZO0mtTHAgg9QVscLVtwCcQ7Hgx.jpg',
      backdrop_path: '/AftVTQuXw2R0SZkSLPZ4aZB72LJ.jpg',
      overview:
        'Are you happy? With this question, Zoa and four other attractive young people, very active on social networks, are invited to the most exclusive party in history on a secret island, organized by the brand of a new drink. What begins as an exciting journey will soon become the journey of a lifetime. But paradise is not really what it seems - Welcome to Eden.',
      genre_ids: [10759],
      first_air_date: '2022-05-06',
      popularity: 111.569,
      media_type: 'tv',
    },
    {
      genre_ids: [80, 18],
      original_language: 'en',
      poster_path: '/9Z7L7wSB6nLwWk7coUgm1ytQbOB.jpg',
      id: 153657,
      vote_average: 9.0,
      overview:
        "Bosch is now making a living as a private investigator two years after he quit the LAPD and finds himself working with one time enemy and top-notch attorney Honey “Money” Chandler. Meanwhile, Bosch's daughter Maddie is venturing into the world of the LAPD.",
      original_name: 'Bosch: Legacy',
      origin_country: ['US'],
      vote_count: 7,
      name: 'Bosch: Legacy',
      backdrop_path: '/wVGiwvE5CtlVPrP0oEO3W70ft6D.jpg',
      first_air_date: '2022-05-05',
      popularity: 46.918,
      media_type: 'tv',
    },
    {
      overview:
        'An enigmatic magician living in an abandoned amusement park introduces magic into the life of a high schooler struggling with harsh realities.',
      name: 'The Sound of Magic',
      backdrop_path: '/tX5W2a0B9r4cs25G78tKjNv76Gj.jpg',
      vote_count: 3,
      genre_ids: [18, 10765],
      origin_country: ['KR'],
      first_air_date: '2022-05-06',
      original_name: '안나라수마나라',
      poster_path: '/jrWM82Hie9DAkoDzXh3pxAFwf9d.jpg',
      id: 123349,
      original_language: 'ko',
      vote_average: 8.3,
      popularity: 74.621,
      media_type: 'tv',
    },
    {
      overview:
        'Depicting an epic 26th-century conflict between humanity and an alien threat known as the Covenant, the series weaves deeply drawn personal stories with action, adventure and a richly imagined vision of the future.',
      name: 'Halo',
      backdrop_path: '/1qpUk27LVI9UoTS7S0EixUBj5aR.jpg',
      vote_count: 572,
      genre_ids: [10759, 10765],
      origin_country: ['US'],
      first_air_date: '2022-03-24',
      original_name: 'Halo',
      poster_path: '/nJUHX3XL1jMkk8honUZnUmudFb9.jpg',
      id: 52814,
      original_language: 'en',
      vote_average: 8.7,
      popularity: 5238.03,
      media_type: 'tv',
    },
    {
      adult: false,
      backdrop_path: '/192vHmAPbk5esL34XMKZ1YLGFjr.jpg',
      genre_ids: [28, 53, 80],
      id: 763285,
      original_language: 'en',
      original_title: 'Ambulance',
      overview:
        "Decorated veteran Will Sharp, desperate for money to cover his wife's medical bills, asks for help from his adoptive brother Danny. A charismatic career criminal, Danny instead offers him a score: the biggest bank heist in Los Angeles history: $32 million.",
      poster_path: '/kuxjMVuc3VTD7p42TZpJNsSrM1V.jpg',
      release_date: '2022-03-16',
      title: 'Ambulance',
      video: false,
      vote_average: 7.0,
      vote_count: 468,
      popularity: 3735.135,
      media_type: 'movie',
    },
    {
      id: 88584,
      first_air_date: '2022-05-05',
      name: 'The Pentaverate',
      backdrop_path: '/6lg8J79bB0jjTCEah9xyBrNtYSU.jpg',
      vote_count: 3,
      genre_ids: [35],
      vote_average: 6.0,
      original_language: 'en',
      original_name: 'The Pentaverate',
      origin_country: ['US'],
      poster_path: '/kY0AKRdYuaahPMcQL2jIxXRHvgf.jpg',
      overview:
        'After influencing global events for centuries, a secret society faces a dangerous threat from within. Can a Canadian reporter save them — and the world?',
      popularity: 92.295,
      media_type: 'tv',
    },
    {
      original_language: 'en',
      id: 113367,
      original_name: 'The Wilds',
      origin_country: ['US'],
      vote_average: 8.0,
      name: 'The Wilds',
      vote_count: 329,
      poster_path: '/gHBtyMdHbWoM3tpM8VZymer8HfF.jpg',
      backdrop_path: '/jke7vRfAfwViuwfJhuhzlpxQuHY.jpg',
      overview:
        "A group of teen girls from different backgrounds must fight for survival after a plane crash strands them on a deserted island. The castaways both clash and bond as they learn more about each other, the secrets they keep, and the traumas they've all endured. But there’s just one twist… these girls did not end up on this island by accident.",
      genre_ids: [9648, 18],
      first_air_date: '2020-12-11',
      popularity: 168.84,
      media_type: 'tv',
    },
    {
      adult: false,
      backdrop_path: '/4rON0QFWpHtZ9bEtfdE68TFbfGr.jpg',
      genre_ids: [53, 27],
      original_language: 'en',
      original_title: 'Escape the Field',
      poster_path: '/3qDumKWwi3YZacMI9u2UoPHWVDi.jpg',
      vote_count: 11,
      video: false,
      vote_average: 6.1,
      title: 'Escape the Field',
      overview:
        'Six strangers suddenly awaken in a remote, endless cornfield. Stripped of their possessions, they are left with only six items: a gun with a single bullet, matches, a lantern, a knife, a compass, and a flask of water. As mysterious sirens blare in the distance and traps appear at every turn, the group realizes it’s been plunged into a cat-and-mouse game with an unseen evil, and survival depends upon solving a diabolical and deadly puzzle.',
      release_date: '2022-05-06',
      id: 739643,
      popularity: 78.59,
      media_type: 'movie',
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};

export const featuredMovieDummy = {
  adult: false,
  backdrop_path: '/AdyJH8kDm8xT8IKTlgpEC15ny4u.jpg',
  belongs_to_collection: {
    id: 618529,
    name: 'Doctor Strange Collection',
    poster_path: '/bm7UlW3ctMJAvD6NNXrCDdRyyKn.jpg',
    backdrop_path: '/5ZuctJh5uX5L2dz1CjA7WsTJwZk.jpg',
  },
  budget: 200000000,
  genres: [
    {
      id: 14,
      name: 'Fantasy',
    },
    {
      id: 28,
      name: 'Action',
    },
    {
      id: 12,
      name: 'Adventure',
    },
  ],
  homepage:
    'https://www.marvel.com/movies/doctor-strange-in-the-multiverse-of-madness',
  id: 453395,
  imdb_id: 'tt9419884',
  original_language: 'en',
  original_title: 'Doctor Strange in the Multiverse of Madness',
  overview:
    'Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.',
  popularity: 5201.375,
  poster_path: '/wRnbWt44nKjsFPrqSmwYki5vZtF.jpg',
  production_companies: [
    {
      id: 420,
      logo_path: '/hUzeosd33nzE5MCNsZxCGEKTXaQ.png',
      name: 'Marvel Studios',
      origin_country: 'US',
    },
  ],
  production_countries: [
    {
      iso_3166_1: 'US',
      name: 'United States of America',
    },
  ],
  release_date: '2022-05-04',
  revenue: 229300000,
  runtime: 126,
  spoken_languages: [
    {
      english_name: 'Cantonese',
      iso_639_1: 'cn',
      name: '广州话 / 廣州話',
    },
    {
      english_name: 'English',
      iso_639_1: 'en',
      name: 'English',
    },
    {
      english_name: 'Spanish',
      iso_639_1: 'es',
      name: 'Español',
    },
  ],
  status: 'Released',
  tagline: 'Enter a new dimension of Strange.',
  title: 'Doctor Strange in the Multiverse of Madness',
  video: false,
  vote_average: 7.6,
  vote_count: 779,
};

export const releaseDatesDummy: ReleaseDates = {
  id: 453395,
  results: [
    {
      iso_3166_1: 'FR',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-04T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'CA',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-06T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'PT',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-05T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'PH',
      release_dates: [
        {
          certification: 'R-13',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-04T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'BR',
      release_dates: [
        {
          certification: '14',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-05T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'DE',
      release_dates: [
        {
          certification: '12',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-05T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'KR',
      release_dates: [
        {
          certification: '12',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-04T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'FI',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-06T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'IL',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-05T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'ES',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-06T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'TH',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-05T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'CZ',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-05T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'AT',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-04T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'SG',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-04T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'GR',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-05T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'SE',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-04T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'AU',
      release_dates: [
        {
          certification: 'M',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-05T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'HK',
      release_dates: [
        {
          certification: 'IIA',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-04T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'PL',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-06T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'TR',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-06T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'JP',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-04T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'GB',
      release_dates: [
        {
          certification: '12A',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-05T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'HU',
      release_dates: [
        {
          certification: '16',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-04T00:00:00.000Z',
          type: 1,
        },
        {
          certification: '16',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-05T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'UA',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-05T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'MK',
      release_dates: [
        {
          certification: '',
          iso_639_1: '',
          note: '',
          release_date: '2022-05-05T00:00:00.000Z',
          type: 3,
        },
      ],
    },
    {
      iso_3166_1: 'US',
      release_dates: [
        {
          certification: 'PG-13',
          iso_639_1: '',
          note: 'Hollywood, California',
          release_date: '2022-05-02T00:00:00.000Z',
          type: 1,
        },
        {
          certification: 'PG-13',
          iso_639_1: null,
          note: '',
          release_date: '2022-05-06T00:00:00.000Z',
          type: 3,
        },
      ],
    },
  ],
};

export const creditsDummy: Credit = {
  id: 453395,
  cast: [
    {
      adult: false,
      gender: 2,
      id: 71580,
      known_for_department: 'Acting',
      name: 'Benedict Cumberbatch',
      original_name: 'Benedict Cumberbatch',
      popularity: 54.511,
      profile_path: '/fBEucxECxGLKVHBznO0qHtCGiMO.jpg',
      cast_id: 2,
      character: 'Dr. Stephen Strange / Sinister Strange / Defender Strange',
      credit_id: '58fa84bbc3a36879f40021db',
      order: 0,
    },
    {
      adult: false,
      gender: 1,
      id: 550843,
      known_for_department: 'Acting',
      name: 'Elizabeth Olsen',
      original_name: 'Elizabeth Olsen',
      popularity: 31.048,
      profile_path: '/mbMsmQE5CyMVTIGMGCw2XpcPCOc.jpg',
      cast_id: 10,
      character: 'Wanda Maximoff / The Scarlet Witch',
      credit_id: '5d33bbc26a300b2f7ea6c7f4',
      order: 1,
    },
    {
      adult: false,
      gender: 2,
      id: 5294,
      known_for_department: 'Acting',
      name: 'Chiwetel Ejiofor',
      original_name: 'Chiwetel Ejiofor',
      popularity: 11.292,
      profile_path: '/kq5DDnqqofoRI0t6ddtRlsJnNPT.jpg',
      cast_id: 12,
      character: 'Baron Karl Mordo',
      credit_id: '5d3b184d60c51d6c6a861ec2',
      order: 2,
    },
    {
      adult: false,
      gender: 2,
      id: 30082,
      known_for_department: 'Acting',
      name: 'Benedict Wong',
      original_name: 'Benedict Wong',
      popularity: 32.076,
      profile_path: '/ukmfsl59Isvn9odgzMWBidA3cmt.jpg',
      cast_id: 3,
      character: 'Wong',
      credit_id: '58fab71dc3a36879be004e6f',
      order: 3,
    },
    {
      adult: false,
      gender: 1,
      id: 1912381,
      known_for_department: 'Acting',
      name: 'Xochitl Gomez',
      original_name: 'Xochitl Gomez',
      popularity: 33.632,
      profile_path: '/oo1wzI9zaRWvZOsae43raoPykgb.jpg',
      cast_id: 29,
      character: 'America Chavez',
      credit_id: '5f89c52be9da69003ae63fc8',
      order: 4,
    },
  ],
  crew: [
    {
      adult: false,
      gender: 2,
      id: 531,
      known_for_department: 'Sound',
      name: 'Danny Elfman',
      original_name: 'Danny Elfman',
      popularity: 4.67,
      profile_path: '/zFladKAPypbzp26Tfyeiy23vanH.jpg',
      credit_id: '602e756b0f3655003f275914',
      department: 'Sound',
      job: 'Original Music Composer',
    },
    {
      adult: false,
      gender: 2,
      id: 943,
      known_for_department: 'Camera',
      name: 'John Mathieson',
      original_name: 'John Mathieson',
      popularity: 1.321,
      profile_path: '/AkWm67UMEWHhF3BDfH32HkRl5oM.jpg',
      credit_id: '603fe1304d679100244fc408',
      department: 'Camera',
      job: 'Director of Photography',
    },
    {
      adult: false,
      gender: 1,
      id: 7232,
      known_for_department: 'Production',
      name: 'Sarah Halley Finn',
      original_name: 'Sarah Halley Finn',
      popularity: 4.834,
      profile_path: '/pI3OhmnHhXLEwuv0Vq6qJHivCJA.jpg',
      credit_id: '6030d94dfab3fa003efd0704',
      department: 'Production',
      job: 'Casting',
    },
    {
      adult: false,
      gender: 2,
      id: 7623,
      known_for_department: 'Directing',
      name: 'Sam Raimi',
      original_name: 'Sam Raimi',
      popularity: 13.972,
      profile_path: '/zQoLMlrwuVYE9KqhVVgo7t5osXl.jpg',
      credit_id: '5e3b5fa3ac8e6b0011cab4cf',
      department: 'Directing',
      job: 'Director',
    },
    {
      adult: false,
      gender: 2,
      id: 7624,
      known_for_department: 'Writing',
      name: 'Stan Lee',
      original_name: 'Stan Lee',
      popularity: 8.231,
      profile_path: '/kKeyWoFtTqOPsbmwylNHmuB3En9.jpg',
      credit_id: '619f1c0cbc2cb30042862359',
      department: 'Writing',
      job: 'Characters',
    },
    {
      adult: false,
      gender: 2,
      id: 7623,
      known_for_department: 'Directing',
      name: 'Sam Raimi',
      original_name: 'Sam Raimi',
      popularity: 11.653,
      profile_path: '/zQoLMlrwuVYE9KqhVVgo7t5osXl.jpg',
      credit_id: '5e3b5fa3ac8e6b0011cab4cf',
      department: 'Directing',
      job: 'Director',
    },
    {
      adult: false,
      gender: 2,
      id: 2094567,
      known_for_department: 'Writing',
      name: 'Michael Waldron',
      original_name: 'Michael Waldron',
      popularity: 4.208,
      profile_path: '/5d6wkYnJgkVAzThqnnwOLNDzACM.jpg',
      credit_id: '5e3de21c98f1f1000f0eac07',
      department: 'Writing',
      job: 'Writer',
    },
  ],
};

export const similarDummy = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/6EnDIsjiel1qOfsIKQInwl80Zua.jpg',
      genre_ids: [16, 878],
      id: 55931,
      title: 'The Animatrix',
      original_language: 'en',
      original_title: 'The Animatrix',
      overview:
        "Straight from the creators of the groundbreaking Matrix trilogy, this collection of short animated films from the world's leading anime directors fuses computer graphics and Japanese anime to provide the background of the Matrix universe and the conflict between man and machines. The shorts include Final Flight of the Osiris, The Second Renaissance, Kid's Story, Program, World Record, Beyond, A Detective Story and Matriculated.",
      popularity: 19.808,
      poster_path: '/eDjIG2hAeMU5cxLrd6oiQqdqoZt.jpg',
      release_date: '2003-05-09',
      video: false,
      vote_average: 7.174,
      vote_count: 1230,
    },
    {
      adult: false,
      backdrop_path: '/fuSYapxTCfkH2wKDmUjRso8UEdz.jpg',
      genre_ids: [10751, 16],
      id: 44874,
      title: 'Barbie: A Fashion Fairytale',
      original_language: 'en',
      original_title: 'Barbie: A Fashion Fairytale',
      overview:
        "Join Barbie in a colourful, modern-day fairytale filled with fashion, friends and fun! Barbie and her dog Sequin jet off to visit her Aunt's amazing fashion house in Paris, and much to her surprise it's about to be shut down forever. After she discovers three enchanting Flairies with sparkle-magic powers, Barbie comes up with a brilliant idea to save the business. She even inspires Alice, a shy fashion designer, and together they create a dazzling runway fashion show. Barbie shows that magic happens when you believe in yourself.",
      popularity: 61.658,
      poster_path: '/bFnf8f8DXdCANQ7Y62djgubhh4P.jpg',
      release_date: '2010-09-14',
      video: false,
      vote_average: 7.215,
      vote_count: 585,
    },
    {
      adult: false,
      backdrop_path: '/2PKMeD171nYXR3J77fD3GKl1zfl.jpg',
      genre_ids: [28, 80, 18, 53],
      id: 49026,
      title: 'The Dark Knight Rises',
      original_language: 'en',
      original_title: 'The Dark Knight Rises',
      overview:
        "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.",
      popularity: 88.097,
      poster_path: '/85cWkCVftiVs0BVey6pxX8uNmLt.jpg',
      release_date: '2012-07-16',
      video: false,
      vote_average: 7.766,
      vote_count: 19487,
    },
    {
      adult: false,
      backdrop_path: '/yeF9ewBnFp9d5nqdHMic4IAOqrs.jpg',
      genre_ids: [28, 878],
      id: 49049,
      title: 'Dredd',
      original_language: 'en',
      original_title: 'Dredd',
      overview:
        'In the future, America is a dystopian wasteland. The latest scourge is Ma-Ma, a prostitute-turned-drug pusher with a dangerous new drug and aims to take over the city. The only possibility of stopping her is an elite group of urban police called Judges, who combine the duties of judge, jury and executioner to deliver a brutal brand of swift justice. But even the top-ranking Judge, Dredd, discovers that taking down Ma-Ma isn’t as easy as it seems in this explosive adaptation of the hugely popular comic series.',
      popularity: 17.213,
      poster_path: '/wLx65gtGVnUFCxceHWGszcruCZj.jpg',
      release_date: '2012-09-07',
      video: false,
      vote_average: 6.788,
      vote_count: 4125,
    },
    {
      adult: false,
      backdrop_path: '/sKWh9hF0ekVhHHyGuJwdA3fnMGZ.jpg',
      genre_ids: [10749, 878, 18, 14],
      id: 58244,
      title: 'Upside Down',
      original_language: 'en',
      original_title: 'Upside Down',
      overview:
        'In an alternate universe where twinned worlds have opposite gravities, a young man battles interplanetary prejudice and the laws of physics in his quest to reunite with the long-lost girl of his dreams in this visually stunning romantic adventure that poses the question: what if love was stronger than gravity?',
      popularity: 16.257,
      poster_path: '/2Td1nknvCcpc03EtgKULNH2PEjI.jpg',
      release_date: '2012-09-27',
      video: false,
      vote_average: 6.24,
      vote_count: 2179,
    },
    {
      adult: false,
      backdrop_path: '/4hCDuBCG1oSKFfr4TKLOJG30JzV.jpg',
      genre_ids: [28, 12, 80],
      id: 59859,
      title: 'Kick-Ass 2',
      original_language: 'en',
      original_title: 'Kick-Ass 2',
      overview:
        'After Kick-Ass’ insane bravery inspires a new wave of self-made masked crusaders, he joins a patrol led by the Colonel Stars and Stripes. When these amateur superheroes are hunted down by Red Mist — reborn as The Mother Fucker — only the blade-wielding Hit-Girl can prevent their annihilation.',
      popularity: 42.543,
      poster_path: '/4LUzG0blTn6JMhUwXSmjPqNFNXL.jpg',
      release_date: '2013-07-17',
      video: false,
      vote_average: 6.4,
      vote_count: 5279,
    },
    {
      adult: false,
      backdrop_path: '/58r049aVTO1KjAYVuWJr0KgG5nY.jpg',
      genre_ids: [12, 28, 53, 878],
      id: 44912,
      title: 'Green Lantern',
      original_language: 'en',
      original_title: 'Green Lantern',
      overview:
        'For centuries, a small but powerful force of warriors called the Green Lantern Corps has sworn to keep intergalactic order. Each Green Lantern wears a ring that grants him superpowers. But when a new enemy called Parallax threatens to destroy the balance of power in the Universe, their fate and the fate of Earth lie in the hands of the first human ever recruited.',
      popularity: 66.561,
      poster_path: '/fj21HwUprqjjwTdkKC1XZurRSpV.jpg',
      release_date: '2011-06-16',
      video: false,
      vote_average: 5.165,
      vote_count: 6191,
    },
    {
      adult: false,
      backdrop_path: '/69EFgWWPFWbRNHmQgYdSnyJ94Ge.jpg',
      genre_ids: [28, 12, 14, 878],
      id: 49521,
      title: 'Man of Steel',
      original_language: 'en',
      original_title: 'Man of Steel',
      overview:
        'A young boy learns that he has extraordinary powers and is not of this earth. As a young man, he journeys to discover where he came from and what he was sent here to do. But the hero in him must emerge if he is to save the world from annihilation and become the symbol of hope for all mankind.',
      popularity: 83.012,
      poster_path: '/7rIPjn5TUK04O25ZkMyHrGNPgLx.jpg',
      release_date: '2013-06-12',
      video: false,
      vote_average: 6.585,
      vote_count: 13124,
    },
    {
      adult: false,
      backdrop_path: '/kw4GhCZP5NeMVsfPol6HcX9JEeQ.jpg',
      genre_ids: [10770, 28, 12, 14, 878],
      id: 50468,
      title: 'Dr. Strange',
      original_language: 'en',
      original_title: 'Dr. Strange',
      overview:
        'A psychiatrist becomes the new Sorcerer Supreme of the Earth in order to battle an evil Sorceress from the past.',
      popularity: 248.897,
      poster_path: '/uMoUh0cgZmAfbVF1aF9WGRfXKoh.jpg',
      release_date: '1978-09-06',
      video: false,
      vote_average: 6.338,
      vote_count: 71,
    },
    {
      adult: false,
      backdrop_path: '/tKa1gmGKAUVYnflYcadipeL3d9h.jpg',
      genre_ids: [28, 12, 878],
      id: 68721,
      title: 'Iron Man 3',
      original_language: 'en',
      original_title: 'Iron Man 3',
      overview:
        "When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.",
      popularity: 107.23,
      poster_path: '/qhPtAc1TKbMPqNvcdXSOn9Bn7hZ.jpg',
      release_date: '2013-04-18',
      video: false,
      vote_average: 6.933,
      vote_count: 19442,
    },
    {
      adult: false,
      backdrop_path: '/a4KUVG5P5hBSgAgHHindbnyubTF.jpg',
      genre_ids: [14, 12, 10751],
      id: 68728,
      title: 'Oz the Great and Powerful',
      original_language: 'en',
      original_title: 'Oz the Great and Powerful',
      overview:
        "Oscar Diggs, a small-time circus illusionist and con-artist, is whisked from Kansas to the Land of Oz where the inhabitants assume he's the great wizard of prophecy, there to save Oz from the clutches of evil.",
      popularity: 28.382,
      poster_path: '/7lBgN59T5m1DaC9XcLkHOXdK9ax.jpg',
      release_date: '2013-03-07',
      video: false,
      vote_average: 5.887,
      vote_count: 5906,
    },
    {
      adult: false,
      backdrop_path: '/aTGvZ3F8QnAD8cPpJRaaqRRxFK6.jpg',
      genre_ids: [28, 12, 14],
      id: 68735,
      title: 'Warcraft',
      original_language: 'en',
      original_title: 'Warcraft',
      overview:
        'The peaceful realm of Azeroth stands on the brink of war as its civilization faces a fearsome race of invaders: orc warriors fleeing their dying home to colonize another. As a portal opens to connect the two worlds, one army faces destruction and the other faces extinction. From opposing sides, two heroes are set on a collision course that will decide the fate of their family, their people, and their home.',
      popularity: 43.586,
      poster_path: '/nZIIOs06YigBnvmlJ2hxZeA8eTO.jpg',
      release_date: '2016-05-25',
      video: false,
      vote_average: 6.344,
      vote_count: 5765,
    },
    {
      adult: false,
      backdrop_path: '/wPZPiHsd7Oz3vg3IuVRtSHBY9iU.jpg',
      genre_ids: [12, 14],
      id: 68737,
      title: 'Seventh Son',
      original_language: 'en',
      original_title: 'Seventh Son',
      overview:
        "John Gregory, who is a seventh son of a seventh son and also the local spook, has protected the country from witches, boggarts, ghouls and all manner of things that go bump in the night. However John is not young anymore, and has been seeking an apprentice to carry on his trade. Most have failed to survive. The last hope is a young farmer's son named Thomas Ward. Will he survive the training to become the spook that so many others couldn't?",
      popularity: 42.378,
      poster_path: '/7Q8DfXSjcFSSQDOxz1Sk865wNqI.jpg',
      release_date: '2014-12-12',
      video: false,
      vote_average: 5.473,
      vote_count: 2177,
    },
    {
      adult: false,
      backdrop_path: '/uhYoytlNaq46dG81wLmHqaSuzWu.jpg',
      genre_ids: [28, 12, 14],
      id: 76338,
      title: 'Thor: The Dark World',
      original_language: 'en',
      original_title: 'Thor: The Dark World',
      overview:
        'Thor fights to restore order across the cosmos… but an ancient race led by the vengeful Malekith returns to plunge the universe back into darkness. Faced with an enemy that even Odin and Asgard cannot withstand, Thor must embark on his most perilous and personal journey yet, one that will reunite him with Jane Foster and force him to sacrifice everything to save us all.',
      popularity: 107.903,
      poster_path: '/wp6OxE4poJ4G7c0U2ZIXasTSMR7.jpg',
      release_date: '2013-10-30',
      video: false,
      vote_average: 6.578,
      vote_count: 14828,
    },
    {
      adult: false,
      backdrop_path: '/KBe9fHU5rVg4daoKnFwl1Cbc28.jpg',
      genre_ids: [12, 14, 18],
      id: 58595,
      title: 'Snow White and the Huntsman',
      original_language: 'en',
      original_title: 'Snow White and the Huntsman',
      overview:
        'After the Evil Queen marries the King, she performs a violent coup in which the King is murdered and his daughter, Snow White, is taken captive. Almost a decade later, a grown Snow White is still in the clutches of the Queen. In order to obtain immortality, The Evil Queen needs the heart of Snow White. After Snow escapes the castle, the Queen sends the Huntsman to find her in the Dark Forest.',
      popularity: 39.804,
      poster_path: '/8HUa5kRubYbnAD5UVpnhTGGgMTW.jpg',
      release_date: '2012-05-30',
      video: false,
      vote_average: 5.96,
      vote_count: 7006,
    },
    {
      adult: false,
      backdrop_path: '/fHx9e35Vn7mMH3O0Fmfds70ABo8.jpg',
      genre_ids: [28, 878, 10752],
      id: 13995,
      title: 'Captain America',
      original_language: 'en',
      original_title: 'Captain America',
      overview:
        'During World War II, a brave, patriotic American Soldier undergoes experiments to become a new supersoldier, "Captain America". Racing to Germany to sabotage the rockets of Nazi baddie "Red Skull", Captain America winds up frozen until the 1990s. He reawakens to find that the Red Skull has changed identities and is now planning to kidnap the President of the United States.',
      popularity: 16.691,
      poster_path: '/lUsDBhzogxYOU5XshARgnnZY4Xd.jpg',
      release_date: '1990-12-14',
      video: false,
      vote_average: 4.646,
      vote_count: 326,
    },
    {
      adult: false,
      backdrop_path: '/knGLovXkm31p071kbshxLqevB0N.jpg',
      genre_ids: [28, 35, 80, 14],
      id: 9470,
      title: 'Kung Fu Hustle',
      original_language: 'cn',
      original_title: '功夫',
      overview:
        "It's the 1940s, and the notorious Axe Gang terrorizes Shanghai. Small-time criminals Sing and Bone hope to join, but they only manage to make lots of very dangerous enemies. Fortunately for them, kung fu masters and hidden strength can be found in unlikely places. Now they just have to take on the entire Axe Gang.",
      popularity: 25.967,
      poster_path: '/exbyTbrvRUDKN2mcNEuVor4VFQW.jpg',
      release_date: '2004-02-10',
      video: false,
      vote_average: 7.4,
      vote_count: 2114,
    },
    {
      adult: false,
      backdrop_path: '/xWT5F1DNxciNLEMXRl49iq8zvN7.jpg',
      genre_ids: [14, 16, 10751],
      id: 9479,
      title: 'The Nightmare Before Christmas',
      original_language: 'en',
      original_title: 'The Nightmare Before Christmas',
      overview:
        "Tired of scaring humans every October 31 with the same old bag of tricks, Jack Skellington, the spindly king of Halloween Town, kidnaps Santa Claus and plans to deliver shrunken heads and other ghoulish gifts to children on Christmas morning. But as Christmas approaches, Jack's rag-doll girlfriend, Sally, tries to foil his misguided plans.",
      popularity: 60.762,
      poster_path: '/oQffRNjK8e19rF7xVYEN8ew0j7b.jpg',
      release_date: '1993-10-09',
      video: false,
      vote_average: 7.84,
      vote_count: 7488,
    },
    {
      adult: false,
      backdrop_path: '/e7jIX02GiSwsgkU5lMpeKjwq2Zc.jpg',
      genre_ids: [14, 28],
      id: 9480,
      title: 'Daredevil',
      original_language: 'en',
      original_title: 'Daredevil',
      overview:
        'A man blinded in a childhood accident fights crime using his superhumanly-elevated remaining senses.',
      popularity: 27.802,
      poster_path: '/oCDBwSkntYamuw8VJIxMRCtDBmi.jpg',
      release_date: '2003-02-14',
      video: false,
      vote_average: 5.234,
      vote_count: 4216,
    },
    {
      adult: false,
      backdrop_path: '/baJHUXBcoaHnMf2sjwegbuhIjEV.jpg',
      genre_ids: [878],
      id: 9482,
      title: 'Judge Dredd',
      original_language: 'en',
      original_title: 'Judge Dredd',
      overview:
        'In a dystopian future, Dredd, the most famous judge (a cop with instant field judiciary powers) is convicted for a crime he did not commit while his murderous counterpart escapes.',
      popularity: 18.104,
      poster_path: '/aja6BILb8Efe4eJksiPs5pHd5ai.jpg',
      release_date: '1995-06-30',
      video: false,
      vote_average: 5.745,
      vote_count: 1920,
    },
  ],
  total_pages: 500,
  total_results: 10000,
};
